[build]
  command = "npm run build"
  publish = ".next"

# Disable Edge Functions completely
[functions]
  node_bundler = "esbuild"

# Force Node.js environment for all functions
[build.environment]
  NEXT_DISABLE_EDGE_RUNTIME = "1"
  NODE_VERSION = "18"

# Redirect all image optimization requests to bypass Edge Functions
[[redirects]]
  from = "/_next/image*"
  to = "/_next/static/image/:splat"
  status = 200

# Handle 404 errors
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
